In [1]:
import numpy as np

In [11]:
X = np.random.rand(3,4)
print(X)
print(X.shape)
x = X[:,0]
print(x)
print(x.shape)

[[0.60581116 0.26739361 0.97863717 0.38356106]
 [0.34141443 0.71859337 0.21998916 0.28685582]
 [0.99791066 0.30112447 0.78607407 0.57542353]]
(3, 4)
[0.60581116 0.34141443 0.99791066]
(3,)
